services:
  mysql:
    image: mysql:8.0
    container_name: webcrawler_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webcrawler_db
      MYSQL_USER: webcrawler_user
      MYSQL_PASSWORD: your_secure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: webcrawler_app
    depends_on:
      - mysql
    environment:
      DB_USER: webcrawler_user
      DB_PASS: your_secure_password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: webcrawler_db
    ports:
      - "8080:8080"

volumes:
  mysql_data:
