version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: webcrawler_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webcrawler_db
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: webcrawler_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: webcrawler_backend
    ports:
      - "8090:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: webcrawler
      DB_PASSWORD: webcrawler_pass
      DB_NAME: webcrawler_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: go run main.go

volumes:
  mysql_data:
